/*-------------------------------------------------------------------------*/
create table users (
    userid integer generated by default as identity primary key,
    username varchar(100) not null unique,
    password varchar(100) not null,
    firstname varchar(100) not null,
    lastname varchar(100) not null,
    motto varchar(500),
    birthday date not null,
    isadmin boolean not null default false
);

insert into users(userid,username,password,firstname,lastname,motto,birthday,isadmin) values 
(default,'giomast','mondialcasa','Giorgio','Mastrota','Alza la cornetta! Mondial Casa ti aspetta!','1950-1-1',false),
(default,'mikebon','ruotafortuna','Mike','Bongiorno','Allegriaaaaaaaaaaaaa','1850-12-25',true),
(default,'cheft','miracleblade','Chef','Tony','I coltelli Miracle Blade tagliano pure la marmitta dello zippino','1666-12-25',true);

/*-------------------------------------------------------------------------*/
create table walls (
    wallid integer generated by default as identity primary key,
    owner varchar(100) references users(username),
    name varchar(100) default NULL
);

insert into walls(wallid,owner,name) values
(default,'giomast',NULL),
(default,'mikebon',NULL),
(default,'cheft',NULL),
(default,'giomast','Tarantallegra'),
(default,'mikebon','Telespettatori');

/*-------------------------------------------------------------------------*/
/*-----------------------------MODIFICATO DATE IN DATETIME ----------------*/
create table posts ( 
    postid integer generated by default as identity primary key,
    author varchar(100) references users(username),
    msg varchar(500) not null,
    url varchar(500) default NULL,
	dated timestamp not null
);

insert into posts(postid,author,msg,url,dated) values
(default,'giomast','Post Mastrota 1',NULL,'1991-1-1 11:22:33'),
(default,'giomast','Post Mastrota 2',NULL,'1992-2-2 22:11:12' ),
(default,'giomast','Post Mastrota 3',NULL,'1993-3-3 15:14:16'),
(default,'mikebon','Post Bongiorno 1',NULL,'1994-12-3 21:21:21'),
(default,'mikebon','Post Bongiorno 2',NULL,'1995-4-5 23:59:59');


/*-------------------------------------------------------------------------*/
create table publications (
    postid int references posts(postid),
    wallid int references walls(wallid),
    primary key(postid,wallid)
);

insert into publications(postid,wallid) values
(1,1),
(2,1),
(3,1),
(4,2),
(5,2);


create table friendships (
    friend1 varchar(100) references users(username),
    friend2 varchar(100) references users(username),
    primary key (friend1,friend2)
);

create table subscriptions (
    subscriber varchar(100) references users(username),
    groupwall int references walls(wallid),
    primary key (subscriber, groupwall)
);

insert into subscriptions values ('giomast',4),('mikebon',5);

